#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '👷 Styling, testing and building your project before committing'


yarn format && yarn check-format ||
(
    echo '❌ Prettier Check Failed. Run yarn format, add changes and try commit again ❌';
    false;
)

#  Check ESLint Standards
yarn lint ||
(
    echo '❌ ESLint Check Failed. Make the required changes listed above, add changes and try commit again ❌'
    false;
)

# Check tsconfig standars
yarn check-types ||
(
    echo '❌ Failed Type check! Make the changes required above ❌'
    false;
)

# If everything passes... Now we can commit 
echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

yarn build ||
(
    echo '❌ Your build is failed! Next build failed! View the errors above to see why ❌'
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'